name: wse
favicon: null
layout_spectrum: 0.4177087848074734
typography_spectrum: 0.07897497527301311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8400567783974111
  lightness: 0.9810437036212534
  saturation: 0.26195368147455156
  rhythmicContrast: 0.18570633605122566
purpose: []
