name: wse
favicon: null
layout_spectrum: 0.74627
typography_spectrum: 0.58648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8fff7'
    - '#08090d'
    - '#504448'
    - '#7e7070'
    - '#b50f27'
  brandStrength: 0.8400567783974111
  lightness: 0.9810437036212534
  saturation: 0.26195368147455156
  rhythmicContrast: 0.18570633605122566
purpose: []
